version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: api_express_typescript_hello-world_rbac
    container_name: api_express_typescript_hello-world_rbac
    ports:
      - 6060:6060
